displayName: CAS Authentication
type: middleware
iconPath: .assets/icon.png
import: github.com/xezpeleta/traefik-cas-auth
summary: Apereo CAS SSO authentication middleware for Traefik
testData:
  casServerURL: https://cas.example.com
  serviceURLPattern: mydomain.com